[package]
name = "neural"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { git = "https://github.com/tracel-ai/burn.git", features = ["dataset", "wgpu"] }
syntree = "0.14.5"
analysis = { path = "../analysis" }