# check=skip=FromPlatformFlagConstDisallowed
FROM --platform=linux/amd64 ubuntu:22.04 AS rust
ENV DEBIAN_FRONTEND=noninteractive PYO3_PYTHON=python3.13

RUN apt-get update && apt-get install -y software-properties-common curl build-essential pkg-config libssl-dev
RUN add-apt-repository -y ppa:deadsnakes/ppa && apt-get install -y python3.13-dev

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
    | sh -s -- -y --default-toolchain nightly \
    && echo 'export PATH=$HOME/.cargo/bin:$PATH' >> /root/.bashrc

ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /src

COPY Cargo.lock .
COPY docker/Cargo.neural Cargo.toml

COPY ast ./ast
COPY macros ./macros
COPY neural ./neural
COPY util ./util

WORKDIR /src/neural

RUN cargo build --release

FROM --platform=linux/amd64 ghcr.io/astral-sh/uv:latest AS uv
FROM --platform=linux/amd64 nvidia/cuda:12.9.1-cudnn-runtime-ubuntu22.04 AS runtime
ENV DEBIAN_FRONTEND=noninteractive PYO3_PYTHON=python3.13

RUN apt-get update && apt-get install -y software-properties-common build-essential openssh-server tmux vim btop && \
    add-apt-repository -y ppa:deadsnakes/ppa && apt-get install -y python3.13-dev
COPY --from=uv /uv /uvx /bin/

WORKDIR /src
COPY neural/py/uv.lock .
COPY neural/py/pyproject.toml .

RUN uv venv
RUN . .venv/bin/activate
RUN uv pip install torch
RUN uv sync --no-build-isolation

COPY --from=rust /src/target/release/neural /bin/

WORKDIR /
COPY --chmod=0755 docker/start.sh .
CMD [ "./start.sh" ]
