from numpy.typing import NDArray
from torch import nn, optim, manual_seed
from torch.utils.data import random_split
from torch.utils.data.dataset import Dataset
from torch_geometric.loader import DataLoader
from torch_geometric.data import Data
import torch
from actor import Actor
from critic import Critic
from hdbscan import HDBSCAN
import numpy as np
import itertools
from collections import defaultdict

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'mps' if torch.backends.mps.is_available() else 'cpu')

class GraphDataset(Dataset):
    def __init__(self, graphs: list[Data]):
        super().__init__()
        self.graphs = graphs
        # for i, graph in enumerate(self.graphs):
        #     graph.key_index = i

    def __len__(self):
        return len(self.graphs)

    def get(self, idx: int):
        return self.graphs[idx]

    def __getitem__(self, lookup):
        return self.get(lookup)

def generate_dataset(edges: list[NDArray], features: list[NDArray], feature_spans: list[NDArray]) -> GraphDataset:
    assert len(edges) == len(features), "Invalid shape configuration!!! Stack of edges must have same number of graphs as features!"
    # assert edges[0].shape[0] == 2, "Invalid edge shape! Must have shape [B, 2, E]"

    # Iterate over each batch
    # Since the y values are only relevant for the entire graph, they will be stored separately
    # However since the indexing is sensitive the y value for each graph will just be its index
    graphs = []
    for i in range(len(edges)):
        edge_index = edges[i]
        x = features[i]

        # Padding will always be at the end of these, so easy to just get rid of them
        valid_nodes = ~(x == -1).all(axis=1)  # Boolean mask for real nodes
        x_pruned = x[valid_nodes]  # Filter node features

        valid_edges = ~(edge_index == -1).all(axis=0)  # Boolean mask for real edges
        edge_index_pruned = edge_index[:, valid_edges]  # Remove invalid edges

        graphs.append(Data(
            x=torch.tensor(x_pruned, dtype=torch.float),
            edge_index=torch.tensor(edge_index_pruned, dtype=torch.long),
            # This is the only way I could get this to not freak out for some reason
            key_index=f"{i}",
            lines=torch.tensor(feature_spans[i], dtype=torch.long),
        ))

    stats = np.sum(list(map(lambda g: np.array([g.x.shape[0], g.edge_index.shape[1]]), graphs)), 0)
    print(f'📶 Dataset generated with {len(graphs)} entries, {stats[0]} features, {stats[1]} edges')
    return GraphDataset(graphs)

NUM_EPISODES = 25

def make_splits(dataset_sz: int) -> tuple[int, int, int]:
    # Define split sizes (80% Train, 10% Val, 10% Test)
    train_size = int(0.8 * dataset_sz)
    val_size = int(0.1 * dataset_sz)
    test_size = dataset_sz - train_size - val_size  # Ensure correct total
    return train_size, val_size, test_size

def find_relevant_keys_for_clustering(keys: dict[tuple[int, int], NDArray], selected_indices_for_batch: list[tuple[int, int]]) -> dict[tuple[int, int], NDArray]:
    """
    Takes the main `keys` dict and filters to only graph indices present in the batch
    """
    persistent_graph_ids = list(map(lambda i: i[0], selected_indices_for_batch))
    pairs = set(itertools.combinations(persistent_graph_ids, 2))
    out = { k: keys[k] for k in keys.keys() if k in pairs }
    return out

# def min_max_indices(tensor: torch.Tensor):
#     """
#     Find the minimum and maximum indices for each unique number in the tensor.

#     Args:
#         tensor (torch.Tensor): Input tensor with numbers.

#     Returns:
#         results (dict): A dictionary where keys are unique values, and values
#                         are tuples containing the min and max index of occurrences.
#     """
#     # Get all unique values
#     unique_values = torch.unique(tensor)
#     results = {}

#     for value in unique_values:
#         # Find indices of this value in the tensor
#         indices = torch.where(tensor == value)[0]

#         # Calculate min and max indices
#         min_index = torch.min(indices).item()
#         max_index = torch.max(indices).item()

#         # Store results
#         results[value.item()] = (min_index, max_index)

#     return results

def create_line_number_mappings(merge_map: NDArray, original_line_mappings: NDArray) -> NDArray:
    """
    Takes the `merge_map` of shape `[N]` generated by the model run and `original_line_mappings` of shape `[N, 2]`
    Uses an iterative algorithm to determine merges for each item in the merge map.
    The returned tensor contains the feature and it's start and end line numbers
    """
    assert merge_map.shape[0] == original_line_mappings.shape[0], "Invalid arrays!"
    num_features = np.unique(merge_map).shape[0]
    # assert num_features <= merge_map.shape[0], "Num features must be lte size of merge map"
    line_mappings = np.zeros([num_features, 2], dtype=np.long)
    # print(f'Original merge map size {merge_map.shape}')
    # print(f'Made line mappings {line_mappings.shape}')
    # The lookup key is the target merge, the values are all nodes that were merged into it
    lookup = {}
    for i, itm in enumerate(merge_map.tolist()):
        if itm in lookup:
            lookup[itm].append(i)
        else:
            lookup[itm] = [i]

    # print(f'LOOKUP DATA: {lookup}')

    for target, values in lookup.items():
        min_num = 999999999
        max_num = -1
        for merge_src in values:
            row = original_line_mappings[merge_src]
            low = row[0]
            high = row[1]
            min_num = min(min_num, low)
            max_num = max(max_num, high)

        line_mappings[target] = np.array([min_num, max_num])

    return line_mappings

def recombine_per_graph_spans(
    batch: NDArray,                         # [N] graph‐ID per pooled node
    recovered_per_graph: list[NDArray],      # list of [n_g,2] arrays, one per graph in same order
    selected_indices_for_batch
) -> NDArray:
    """
    Given:
      - batch:           length‐N array, batch[i] = graph‐ID of node i
      - recovered_per_graph[k]: array [n_k,2] for graph k,
         in the same order as your `for (pid, graph) in selected_indices`
    Returns:
      - full_spans: np.ndarray of shape [N,2],
         where full_spans[i] is the span for node i.
    """
    N = batch.shape[0]
    full_spans = np.zeros((N,2), dtype=recovered_per_graph[0].dtype)

    # Suppose your graph‐loop was in this order:
    #   for idx, (pid, graph) in enumerate(selected_indices_for_batch):
    for idx, (_, graph) in enumerate(selected_indices_for_batch):
        mask = (batch == graph)              # boolean mask of shape [N]
        spans = recovered_per_graph[idx]     # shape [mask.sum(), 2]
        # sanity check:
        assert spans.shape[0] == mask.sum(), f"Spans don't match mask: ({spans.shape[0]} != {mask.sum()})"
        full_spans[mask] = spans             # broadcast assign into those rows

    return full_spans

def cluster_and_calculate_reward(
    nodes: NDArray,
    keys: dict[tuple[int, int], NDArray],
    merge_map: NDArray,
    selected_indices_for_batch: list[tuple[int, int]],
    selected_line_assignments_for_batch: NDArray,
    batch: NDArray,
    perm: NDArray,
) -> float:
    assert not np.isnan(np.sum(nodes)), "NaN in nodes! Bad training :("
    assert batch.shape[0] == nodes.shape[0], "Something is wrong, nodes must match batch"
    # print(f'BART {batch.shape}')
    # print(f'LAFB {selected_line_assignments_for_batch} ({selected_line_assignments_for_batch.shape})')
    # print(f'SIFB: {selected_indices_for_batch}')
    line_assignments = []
    # print('Processing (graph, pid): ', end='')
    for (persistent_id, graph) in selected_indices_for_batch:
        # print(f'{graph, persistent_id};', end='')
        # relevant_indices = np.where(batch == graph)[0]
        # line_assignments_for_graph = selected_line_assignments_for_batch[relevant_indices]
        # merge_map_for_graph = merge_map[relevant_indices]
        # # print(line_assignments_for_graph)
        # print("Merge Map:")
        # print(merge_map_for_graph)
        # print("LAFG:")
        # print(line_assignments_for_graph)
        # assert line_assignments_for_graph.shape[0] == merge_map_for_graph.shape[0]

        mask = (batch == graph)      # select survivors of that graph
        local_pos = np.nonzero(mask)[0]              # e.g. [ 0, 3, 5, 9, ... ]  length N_graph

        if local_pos.size == 0:
            # no nodes survived for this graph → skip or record an empty array
            print(f'No nodes survived graph pid {persistent_id}')
            line_assignments.append(np.zeros((0, 2), dtype=int))
            continue

        global_nodes = perm[local_pos]         # now these are the true original indices

        # pull out their merge_map entries in the global map:
        merge_map_for_graph = merge_map[global_nodes]

        # now you have numbers in the range 0..N₀–1, but only for this graph’s survivors
        # if you need them 0..N_graph–1, remap:
        uniques = np.unique(merge_map_for_graph)
        remap = {orig:i for i,orig in enumerate(uniques)}
        merge_map_for_graph = np.array([ remap[v] for v in merge_map_for_graph ])

        # and likewise your line spans:
        line_assignments_for_graph = selected_line_assignments_for_batch[global_nodes]

        recovered_assignments = create_line_number_mappings(merge_map_for_graph, line_assignments_for_graph)

        # Build per-node spans:
        node_spans = recovered_assignments[ merge_map_for_graph ]

        assert nodes[mask].shape[0] == node_spans.shape[0], f"Nodes for graph don't match assignments! {nodes[mask].shape[0]} != {recovered_assignments.shape[0]}"
        line_assignments.append(node_spans)
    # print()
    line_assignments = recombine_per_graph_spans(batch, line_assignments, selected_indices_for_batch)
    assert line_assignments.shape[0] == nodes.shape[0], "Nodes don't match line assignments!"
    line_spans = line_assignments
    # print(line_assignments)

    relevant = find_relevant_keys_for_clustering(keys, selected_indices_for_batch)
    print(f'Relevant keys for clustering: {relevant}')
    # If there aren't any relevant keys in this dataset then no change in score
    if len(relevant) == 0:
        return 0.0

    # No prediction data for now, maybe later but get it working without first
    clusterer = HDBSCAN(
        min_cluster_size=2,
        core_dist_n_jobs=-1,
        # prediction_data=True,
        cluster_selection_method='leaf',
        allow_single_cluster=True
    ).fit(nodes)
    labels = clusterer.labels_
    print(f'{labels.max()} clusters created')
    # print('Finding all points membership vectors...')
    # vecs = all_points_membership_vectors(clusterer)

    cluster_dict = defaultdict(list)
    for idx, label in enumerate(labels):
        cluster_dict[label].append(idx)

    # If you want a plain dict instead of defaultdict:
    cluster_dict = dict(cluster_dict)

    # print(vecs)
    # Look through the returned set of membership
    # For each pair in the relevant keys, see if a pair exists in the generated clusters
    # If they do, add points. If not, subtract
    # If there are any clusters unaccounted for, return a negative value for now to
    # disincentivise false positive
    # score = 0.0
    # for cluster_members in cluster_dict.values():
    #     print(f'CLUSTER MEMBERSHIPS: {cluster_members}')
    #     pass

    # 1) Cluster
    # clusterer = HDBSCAN(min_cluster_size=2, cluster_selection_method='leaf')
    clusterer = HDBSCAN(
        min_cluster_size=2,
        core_dist_n_jobs=-1,
        # prediction_data=True,
        cluster_selection_method='leaf',
        allow_single_cluster=True
    )
    labels = clusterer.fit_predict(nodes)   # -1 = noise

    # 2) Recover per‐node spans
    #    If you want "true" spans per node from your original mapping,
    #    you can call the helper above. Otherwise assume line_spans is already per node.

    # 3) Build lookup: local_idx -> (pid,graph)
    # pid_graph = {i: selected_indices_for_batch[i] for i in range(len(selected_indices_for_batch))}

    # 4) Count TP/FP and track which key‐rows we match exactly
    TP = FP = 0
    matched = set()   # (pair, (si,sj,ei,ej))

    # all_keys = set(keys.keys())

    for cluster in set(labels):
        if cluster < 0: continue
        members = np.where(labels == cluster)[0]
        for i, j in itertools.combinations(members, 2):
            g_i = batch[i]
            g_j = batch[j]


            # print(f"SEL {i}, {j}")
            # pid_i, g_i = pid_graph[i]
            # pid_j, g_j = pid_graph[j]
            if g_i == g_j: continue

            pid_i = pid_j = -1

            for pid, g in selected_indices_for_batch:
                if g == g_i:
                    pid_i = pid
                elif g == g_j:
                    pid_j = pid
                # Early return if both found
                if pid_i > -1 and pid_j > -1:
                    break

            span_i = tuple(line_spans[i].tolist())
            span_j = tuple(line_spans[j].tolist())

            pair = (pid_i, pid_j)
            arr = keys.get(pair, None)
            if arr is None or arr.size == 0:
                # no true spans → false positive
                FP += 1
                continue

            # want to see [si, sj, ei, ej]
            want1 = (span_i[0], span_j[0], span_i[1], span_j[1])
            want2 = (span_j[0], span_i[0], span_j[1], span_i[1])

            found = False
            for row in arr:
                row_t = (int(row[0]), int(row[1]), int(row[2]), int(row[3]))
                if row_t == want1 or row_t == want2:
                    TP += 1
                    matched.add((pair, row_t))
                    found = True
                    break
            if not found:
                FP += 1

    # 5) Count FN: ground‐truth rows never matched
    FN = 0
    for pair, arr in keys.items():
        if arr.size == 0: continue
        for row in arr:
            row_t = (int(row[0]), int(row[1]), int(row[2]), int(row[3]))
            if (pair, row_t) not in matched:
                FN += 1

    # 6) Precision/Recall/F1
    precision = TP / (TP + FP) if TP + FP > 0 else 0.0
    recall    = TP / (TP + FN) if TP + FN > 0 else 0.0
    f1 = 2 * precision * recall / (precision + recall) if precision + recall > 0 else 0.0

    print(f"True Positives: {TP}\nFalse Positives: {FP}\nFalse Negatives: {FN}\nF1: {f1}")

    return f1

def train(
    dataset: Dataset,
    actor: nn.Module,
    critic: nn.Module,
    actor_optim: optim.Optimizer,
    critic_optim: optim.Optimizer,
    episodes: int,
    keys: dict[tuple[int, int], NDArray],
):
    manual_seed(0xdeadbeef)

    train_set, val_set, test_set = random_split(dataset, make_splits(len(dataset))) #type: ignore

    train_data = DataLoader(train_set, batch_size=50, shuffle=True) #type: ignore
    val_data = DataLoader(val_set, batch_size=25) #type: ignore
    test_data = DataLoader(test_set, batch_size=25) #type: ignore

    for epoch in range(episodes):
        print(f'\n⏰ EPOCH {epoch}')
        actor.train()
        critic.train()

        total_actor_loss, total_critic_loss = 0.0, 0.0

        # Train
        for batch in train_data:
            print("\n\nNEXT BATCH ->")

            # Selected graph indices are actually different than the assignments given by PyTorch
            # Zip them together for processing later
            selected_indices = batch.key_index
            selected_indices = list(map(int, selected_indices))
            selected_batch_indices = list(range(torch.max(batch.batch) + 1))
            selected_indices = list(zip(selected_indices, selected_batch_indices))

            selected_spans = batch.lines
            batch = batch.to(DEVICE)
            # print(f'SZ: X: {batch.x.shape} B: {batch.batch.shape} E: {batch.edge_index.shape}')
            # print(f'SEL IND: {selected_indices}')
            # print(f'MINMAX: {min_max_indices(batch.batch)}')
            a_x, a_edge_index, merge_map, a_batch, a_perm, a_logp_sum = actor(batch.x, batch.edge_index, batch.batch)
            # print(f"BATCHMAX {torch.max(a_batch)}")
            # print(f'AX: {a_x.shape} MM: {merge_map.shape}')
            # print(merge_map)
            # print(np.where(merge_map.numpy() != np.arange(merge_map.numpy().max() + 1)))
            # assert len(np.unique(merge_map.numpy())) == a_x.shape[0], f"Some merge map entries reference nonexistent nodes! ({len(np.unique(merge_map.numpy()))} != {a_x.shape[0]})"
            pred_reward = critic(batch.x, batch.edge_index, a_x, a_edge_index)
            reward = cluster_and_calculate_reward(
                nodes=a_x.cpu().detach().numpy(),
                keys=keys,
                merge_map=merge_map.cpu().numpy(),
                selected_indices_for_batch=selected_indices,
                selected_line_assignments_for_batch=selected_spans.cpu().numpy(),
                batch=a_batch.cpu().numpy(),
                perm=a_perm.cpu().numpy()
            )

            reward = torch.tensor(reward).to(DEVICE)

            advantage = (reward - pred_reward).detach()
            actor_loss = -(advantage * a_logp_sum).mean()

            actor_optim.zero_grad()
            actor_loss.backward()
            actor_optim.step()

            critic_loss = nn.HuberLoss()(pred_reward, reward)
            critic_optim.zero_grad()
            critic_loss.backward()
            critic_optim.step()

            total_actor_loss += actor_loss
            total_critic_loss += critic_loss

        # Val
        for batch in val_data:
            pass

        print(f'~~\nTotal Loss:\nActor: {total_actor_loss}\nCritic: {total_critic_loss}\n~~')

    # Test
    actor.eval()
    critic.eval()
    for batch in test_data:
        pass

    print('Training complete')

def rust_train(features: list[NDArray], edges: list[NDArray], feature_spans: list[NDArray], keys: dict[tuple[int, int], NDArray]):
    print('✅ Python initialization successful. Beginning training...')
    print(f"KEYS\n\n{keys}\n\n")
    dataset = generate_dataset(edges, features, feature_spans)

    actor = Actor(in_dim=features[0].shape[1], hidden_dims=[20, 20, 20, 10, 10], num_heads=[8, 8, 8, 8, 4], pool_ratios=[0.5, 0.6, 0.8, 0.8, 0.8]).to(DEVICE)
    critic = Critic(in_dim=features[0].shape[1], hidden_dim=20, num_heads=8).to(DEVICE)

    train(
        dataset,
        actor,
        critic,
        optim.Adam(actor.parameters(), lr=0.001),
        optim.Adam(critic.parameters(), lr=0.001),
        NUM_EPISODES,
        keys,
    )
