import os
from collections import defaultdict
from dataclasses import dataclass, field
from typing import Literal, NamedTuple, Optional

import numpy as np
import torch
import torch.nn.functional as F
import torch_scatter
from diskcache import Cache
from numpy.typing import NDArray
from progress import deque
from torch import Tensor
from torch.nn import ModuleList
from torch_geometric.nn import GATv2Conv, LayerNorm
from torch_geometric.utils import k_hop_subgraph, subgraph

DATA_WORKERS = (os.cpu_count() or 1) * 3 // 4
MAX_POOL_TASKS = 100


@dataclass
class ActorConfig:
    alpha: float = 0.9
    beta: float = 0.1
    selection_dropout: float = 0.2
    num_layers: int = 4
    num_heads: int = 4

    entropy_start: float = 0.02
    entropy_end: float = 0.001


@dataclass
class RewardConfig:
    missing_graph_penalty: float = 1.0
    graph_size_penalty: float = 0.1
    removed_graph_reward: float = 0.5
    correct_range_reward: float = 1.1


@dataclass
class GaeConfig:
    gamma: float = 0.99
    lam: float = 0.95


@dataclass
class BatchSizes:
    train: int = 25
    val: int = 25
    test: int = 25


@dataclass
class ModelConfig:
    num_episodes: int = 10

    # Actor
    actor: ActorConfig = field(default_factory=ActorConfig)

    # Reward
    reward: RewardConfig = field(default_factory=RewardConfig)

    gae: GaeConfig = field(default_factory=GaeConfig)

    # Actor optimizer
    actor_lr: float = 1e-5
    actor_wd: float = 1e-5

    # Critic optimizer
    critic_lr: float = 2e-5
    critic_wd: float = 1e-5

    critic_dropout: float = 0.1
    critic_layers: int = 4

    critic_loss_fn: str = "huber"

    embedding_loss_margin: float = 1.0
    embedding_loss_top_k: int = 50

    batch_sizes: BatchSizes = field(default_factory=BatchSizes)


@dataclass
class EvalConfig:
    actor: ActorConfig = field(default_factory=ActorConfig)


class Transition(NamedTuple):
    logp: Optional[torch.Tensor]  # [N]
    reward: torch.Tensor  # [G]
    value: torch.Tensor  # [G]
    batch: Optional[torch.Tensor]
    entropy: Optional[torch.Tensor]


class RunningNorm:
    """
    Code generated by ChatGPT: reward shaping + running normalization + masked critic loss.
    """

    def __init__(self, eps: float = 1e-8):
        self.count = 0.0
        self.mean = 0.0
        self.M2 = 0.0
        self.eps = eps

    def update(self, x: torch.Tensor):
        # x: arbitrary shape; we update with its mean to be robust
        v = x.detach().mean().item()
        self.count += 1.0
        delta = v - self.mean
        self.mean += delta / max(self.count, 1.0)
        delta2 = v - self.mean
        self.M2 += delta * delta2

    @property
    def std(self):
        if self.count < 2:
            return 1.0
        return (self.M2 / (self.count - 1.0)) ** 0.5 + self.eps

    def normalize(self, x: torch.Tensor) -> torch.Tensor:
        return (x - self.mean) / self.std


# --- reward shaping helper ---
def diou_to_reward(
    diou: torch.Tensor,
    mode: Literal["exp", "log", "lin"] = "exp",
    k: float = 4.0,
    pivot: float = 0.5,
    sharp: float = 6.0,
) -> torch.Tensor:
    """
    mode='exp' : r = exp(-k * diou)
    mode='log' : r = sigmoid(sharp * (pivot - diou))
    mode='lin' : r = 1 - diou  (clip later)
    """
    if mode == "exp":
        r = torch.exp(-k * diou)
    elif mode == "log":
        r = torch.sigmoid(sharp * (pivot - diou))
    else:
        r = 1.0 - diou
    return r


# Copied from SO
def lerp(a: float, b: float, t: float) -> float:
    """Linear interpolate on the scale given by a to b, using t as the point on that scale.
    Examples
    --------
        50 == lerp(0, 100, 0.5)
        4.2 == lerp(1, 5, 0.8)
    """
    return (1 - t) * a + t * b


def compute_reward(
    diou_l: Tensor,
    total_keys: int,
    remaining_keys: int,
    batch: Tensor,
    no_key_graph_indices: Tensor,
    size_penalty: float = 0.01,
    missing_graph_penalty: float = 1.0,
    removed_graph_reward: float = 1.0,
    correct_range_reward: float = 1.0,
) -> Tensor:
    """
    diou_l: [N] – node‑wise DIoU (lower is better)
    missing_ratio: float - the number of keys minus the number of missing keys
    batch:  [N] – graph ID for each node
    Returns: [G] – reward per graph
    """
    missing_count = total_keys - remaining_keys
    if len(batch) == 0 and total_keys > 0:
        return torch.full((1,), -missing_count, device=diou_l.device)
    # # Normalise DIoU so that lower = better
    # diou_norm = (diou_l - diou_l.mean()) / (diou_l.std() + 1e-6)

    # # Node‑wise reward = -DIoU (because lower DIoU means more accurate)
    # node_reward = -diou_norm

    node_reward = diou_to_reward(diou=diou_l, mode="log") * correct_range_reward

    # Graph‑wise mean reward
    G = batch.max().item() + 1
    reward_per_graph = torch.zeros(int(G)).to(diou_l.device)
    reward_per_graph = torch_scatter.scatter_mean(
        node_reward, batch, dim=0, out=reward_per_graph
    )

    # Size penalty – encourage fewer nodes
    num_nodes = torch_scatter.scatter_sum(torch.ones_like(diou_l), batch, dim=0)
    reward_per_graph -= size_penalty * num_nodes.float()

    # Missing graph penalty
    reward_per_graph -= missing_graph_penalty * missing_count
    # for event in missing:
    # reward_per_graph[event] -= missing_graph_penalty

    # Removed graph reward: If a graph with no keys was removed, that's good! Give a reward
    # Find all unique members of key batches and actual batches
    # For each item in the no key tensor, if it ISN'T present in the batch then add a reward
    correct_removals = len(no_key_graph_indices) - torch.sum(
        torch.isin(no_key_graph_indices, batch)
    )
    reward_per_graph += correct_removals * removed_graph_reward

    return reward_per_graph


def compute_returns_and_advantages(
    transitions,
    gamma: float = 0.99,
    lam: float = 0.95,
    reward_last_only: bool = False,
    standardize_adv: bool = True,
):
    """assistant-wrote: corrected returns/advantages with per-layer standardization"""
    # Figure out the maximum number of graphs across all transitions
    max_G = max(t.reward.shape[0] for t in transitions)
    L = len(transitions)

    # Pad rewards/values to [L, max_G], and keep a mask
    R = torch.zeros(L, max_G, device=transitions[0].reward.device)
    V = torch.zeros(L, max_G, device=transitions[0].reward.device)
    V_critic = torch.zeros(L, max_G, device=transitions[0].reward.device)
    mask = torch.zeros(L, max_G, dtype=torch.bool, device=R.device)

    for i, t in enumerate(transitions):
        g = t.reward.shape[0]
        R[i, :g] = t.reward
        V[i, :g] = t.value.detach()
        V_critic[i, :g] = t.value
        mask[i, :g] = True

    if reward_last_only:
        R[:-1] = R[-1].unsqueeze(0)

    returns = torch.zeros_like(R)
    gae = torch.zeros(max_G, device=R.device)

    # Compute GAE backwards in time
    for t in reversed(range(L)):
        v_t = V[t]
        v_tp1 = V[t + 1] if t + 1 < L else torch.zeros_like(v_t)
        delta = R[t] + gamma * v_tp1 - v_t
        gae = delta + gamma * lam * gae
        returns[t] = gae + v_t

    advantages = returns - V

    # Mask out invalid graphs
    returns = returns * mask
    advantages = advantages * mask

    if standardize_adv:
        eps = 1e-8
        # avoid dividing by zero for masked-out entries
        mean = (
            advantages.sum(dim=1, keepdim=True)
            / mask.sum(dim=1, keepdim=True).clamp(min=1)
        ).detach()
        var = ((advantages - mean) ** 2 * mask).sum(
            dim=1, keepdim=True
        ) / mask.sum(dim=1, keepdim=True).clamp(min=1)
        std = var.sqrt().clamp(min=eps)
        advantages = (advantages - mean) / std

    advantages = torch.clamp(advantages, -10.0, 10.0)
    return returns, advantages, V_critic, mask


@dataclass
class Metrics:
    actor_loss: Tensor
    critic_loss: Tensor
    reward: Tensor
    value: Tensor
    entropy: Tensor


def auxiliary_embedding_loss(
    embs: Tensor,
    batch: Tensor,
    positives: list[tuple[int, int]],
    top_k: int,
    margin: float,
) -> Optional[Tensor]:
    """
    embs: (N, D)
    batch: (N,)
    positives: list[(A, B)] List of graph pairs that are plagiarized, normalized to batch numbering

    Calculates the embedding loss to aid in clustering
    """

    if not positives:
        return None

    # Build positives adjacency matrix (symmetric)
    G = int(batch.max()) + 1
    positives_tensor = torch.zeros((G, G), dtype=torch.bool, device=embs.device)
    idx = torch.tensor(positives, device=embs.device).T  # shape [2, num_pos]
    positives_tensor[idx[0], idx[1]] = True
    positives_tensor[idx[1], idx[0]] = True
    positives_tensor.fill_diagonal_(True)  # treat self as positive

    N = embs.shape[0]

    # Build batch association masks in one go
    batch_onehot = (
        torch.nn.functional.one_hot(batch, num_classes=G)
        .to(embs.device)
        .to(torch.int)
    )  # [N, G], int

    # For each sample i, mark positives & negatives in its batch
    pos_mask = (batch_onehot @ positives_tensor) > 0  # [N, G], bool
    neg_mask = ~pos_mask

    # Convert from group membership to node membership
    # pos_nodes[i] = bool mask of which nodes are positive wrt batch[i]
    pos_nodes = pos_mask[batch]  # [N, G]
    neg_nodes = neg_mask[batch]  # [N, G]

    # Broadcast to node-level masks
    pos_mask_nodes = (batch_onehot.unsqueeze(0) & pos_nodes.unsqueeze(1)).any(
        -1
    )  # [N, N]
    neg_mask_nodes = (batch_onehot.unsqueeze(0) & neg_nodes.unsqueeze(1)).any(
        -1
    )  # [N, N]

    # Randomly sample top_k positives and negatives for each anchor
    anchors_idx = torch.arange(N, device=embs.device).repeat_interleave(
        top_k * top_k
    )

    pos_indices = []
    neg_indices = []

    for i in range(N):
        pos_pool = torch.where(pos_mask_nodes[i])[0]
        neg_pool = torch.where(neg_mask_nodes[i])[0]
        if len(pos_pool) >= top_k and len(neg_pool) >= top_k:
            pos_sample = pos_pool[
                torch.randperm(len(pos_pool), device=embs.device)[:top_k]
            ]
            neg_sample = neg_pool[
                torch.randperm(len(neg_pool), device=embs.device)[:top_k]
            ]
            # make all pos × neg combinations
            pos_indices.append(pos_sample.repeat_interleave(top_k))
            neg_indices.append(neg_sample.repeat(top_k))

    pos_indices = torch.cat(pos_indices)
    neg_indices = torch.cat(neg_indices)

    anchors = embs[anchors_idx]
    poss = embs[pos_indices]
    negs = embs[neg_indices]

    return F.triplet_margin_loss(anchors, poss, negs, margin=margin)


def auxiliary_embedding_loss_helper(
    embs: Tensor,
    batch,
    persistent_to_batch_id_map: list[tuple[int, int]],
    keys: dict[tuple[int, int], NDArray],
    config: ModelConfig,
):
    pers_to_batch = dict(persistent_to_batch_id_map)

    positives = list(
        map(
            lambda k: (pers_to_batch[k[0]], pers_to_batch[k[1]]),
            filter(
                lambda k: k[0] in pers_to_batch and k[1] in pers_to_batch,
                keys.keys(),
            ),
        )
    )

    aux_emb_loss = auxiliary_embedding_loss(
        embs,
        batch.batch,
        positives=positives,
        top_k=config.embedding_loss_top_k,
        margin=config.embedding_loss_margin,
    )

    return aux_emb_loss


def actor_critic_loss(
    transitions: list[Transition],
    gamma: float = 0.99,
    lam: float = 0.95,
    entropy_coef: float = 0.01,
    critic_loss_fn: str = "huber",
) -> Metrics:
    """
    transitions : list[Transition] – all layers
    returns    : [G]
    advantages : [G]
    """
    returns, advantages, V, mask = compute_returns_and_advantages(
        transitions,
        gamma,
        lam,
    )
    mask = mask.reshape([-1])

    # Policy loss (PG)
    actor_loss = 0.0
    entropy_terms = []
    for i, transition in enumerate(transitions):
        if transition.logp is None:
            continue
        actor_loss += -(
            advantages[i][transition.batch] * transition.logp
        ).mean()
        entropy_terms.append(transition.entropy)

    # Critic loss (smooth L1 / Huber)
    V_all = V.reshape([-1])[mask]
    # V_all = torch.cat([t.value for t in transitions])  # [L, G]
    R_all = torch.cat([returns[t] for t in range(len(returns))])[mask]  # [L, G]
    assert V_all.shape == R_all.shape, (
        f"Shapes mismatch: V_all: {V_all.shape} R_all: {R_all.shape}"
    )

    match critic_loss_fn:
        case "huber":
            critic_loss = F.smooth_l1_loss(V_all, R_all)
        case "mse":
            critic_loss = F.mse_loss(V_all, R_all)
        case _:
            raise ValueError(f"Unknown critic loss function: {critic_loss_fn}")

    # Entropy bonus
    entropy = (
        torch.cat(entropy_terms, dim=0).mean()
        if entropy_terms
        else torch.tensor(0.0, device=transitions[0].reward.device)
    )
    actor_loss -= entropy_coef * entropy

    return Metrics(
        actor_loss=actor_loss,
        critic_loss=critic_loss,
        value=V_all,
        reward=R_all,
        entropy=entropy,
    )


def diou_loss_1d(a: NDArray, b: NDArray) -> NDArray:
    EPSILON = 1e-6

    if a.ndim == 1:
        a = np.expand_dims(a, 0)
    if b.ndim == 1:
        b = np.expand_dims(b, 0)

    assert a.ndim == 2 and b.ndim == 2 and a.shape[1] == b.shape[1] == 2, (
        f"Bad data: a: {a.shape} b: {b.shape}"
    )
    a, b = np.broadcast_arrays(a, b)

    a_center = np.mean(a, axis=1)
    b_center = np.mean(b, axis=1)
    dist_sq = (a_center - b_center) ** 2
    farthest_end = np.max(
        np.hstack([a[:, 1][:, None], b[:, 1][:, None]]), axis=1
    )
    closest_start = np.min(
        np.hstack([a[:, 0][:, None], b[:, 0][:, None]]), axis=1
    )
    outer_distance_sq = (farthest_end - closest_start) ** 2

    start = np.max(np.hstack([a[:, 0][:, None], b[:, 0][:, None]]), axis=1)
    end = np.min(np.hstack([a[:, 1][:, None], b[:, 1][:, None]]), axis=1)
    valid = start < end
    intersection = np.hstack((start[:, None], end[:, None]))
    intersection[~valid] = 0
    intersection = np.diff(intersection, axis=1)
    union = (np.diff(a, axis=1) + np.diff(b, axis=1)) - intersection
    iou_old = intersection / (union + EPSILON)

    # Cleaner impl from ChatGPT
    inter_len = np.clip(end - start, 0, None)
    a_len = a[:, 1] - a[:, 0]
    b_len = b[:, 1] - b[:, 0]
    union = a_len + b_len - inter_len
    iou = inter_len / (union + EPSILON)

    assert np.all(np.equal(iou, iou_old.squeeze(1))), (
        f"DIOU doesnt match old {iou_old.squeeze(1)} != new {iou}"
    )

    return 1.0 - iou + dist_sq / (outer_distance_sq + EPSILON)


def find_closest_mapping_index(line_mappings: NDArray, target: NDArray) -> int:
    return np.argmin(diou_loss_1d(line_mappings, target)).astype(int)


def diou_loss(
    line_mappings: NDArray,
    edge_index: NDArray,
    batch: NDArray,
    keys: NDArray,
    key_batch_associations: NDArray,
    k: int = 5,
    decay_alpha: float = 0.5,
    log_transform_diou: bool = True,
) -> tuple[Tensor, list[int]]:
    """
    Calculates DIoU loss for the closest node in the graph to each key (based on DIoU) and fans out `k` hops
    with decay `decay_alpha`
    """

    assert line_mappings.shape[0] == batch.shape[0], (
        f"line_mappings.shape[0] ({line_mappings.shape[0]}) != batch.shape[0] ({batch.shape[0]})"
    )
    num_nodes = line_mappings.shape[0]

    # Shuffle keys to make it slightly more stochastic
    np.random.shuffle(keys)
    # Find the absolute best nodes (lowest DIoU loss) for each key
    best_node_indices = []
    missing_entry_events = []
    for i, key in enumerate(keys):
        mask = batch == key_batch_associations[i]
        if len(line_mappings[mask]) == 0:
            missing_entry_events += [key_batch_associations[i]] * key.shape[0]
            continue
        map_to_original = np.arange(batch.shape[0])[mask]
        best_node_indices.append(
            map_to_original[
                find_closest_mapping_index(line_mappings[mask], key)
            ]
        )
        # print(f'Best index for {key} is {best_node_indices[-1]} (with value {line_mappings[best_node_indices[-1]]}) from \n {line_mappings[mask]} w/loss\n {diou_loss_1d(line_mappings[mask], key)}')

    # Initialize full loss vector (global node indices)
    losses_full = torch.zeros(num_nodes, dtype=torch.float)

    if len(best_node_indices) == 0:
        return losses_full, missing_entry_events

    # Do k hop subgraph for each key, assigning the DIoU to each node in the graph
    edge_index: Tensor = torch.tensor(edge_index)
    subset, edge_index, mapping, edge_mask = k_hop_subgraph(
        best_node_indices,
        num_hops=k,
        edge_index=edge_index,
        num_nodes=num_nodes,
    )

    # Always want to add DIoU loss since multiple spans can be close enough to eachother for them to overlap

    # ChatGPT made this
    def decay_fn(depth: int):
        return decay_alpha**depth

    # Build adjacency list for full graph
    adj = [[] for _ in range(num_nodes)]
    for src, dst in edge_index.t().tolist():
        adj[src].append(dst)
        adj[dst].append(src)  # if undirected

    # Propagate DIoU loss from each source node
    for i, node_index in enumerate(best_node_indices):
        diou_val = torch.tensor(
            diou_loss_1d(line_mappings[node_index], keys[i])
        )
        if log_transform_diou:
            diou_val = torch.log(diou_val + 1e-8)
        # print(f'Loss for node {node_index} is {diou_val} using {line_mappings[node_index]} and {keys[i]}')

        visited = set()
        queue = deque()
        queue.append((node_index, 0))  # (current_node, depth)

        while queue:
            current, depth = queue.popleft()
            if current in visited or depth > k:
                continue
            visited.add(current)

            losses_full[current] += diou_val.sum(dim=0) * decay_fn(depth)

            if depth < k:
                for neighbor in adj[current]:
                    if neighbor not in visited:
                        queue.append((neighbor, depth + 1))

    return losses_full, missing_entry_events


def create_line_number_mappings(
    merge_map: NDArray, original_line_mappings: NDArray
) -> NDArray:
    """
    Takes the `merge_map` of shape `[N]` generated by the model run and `original_line_mappings` of shape `[N, 2]`
    Uses an iterative algorithm to determine merges for each item in the merge map.
    The returned tensor contains the feature and it's start and end line numbers
    """
    assert merge_map.shape[0] == original_line_mappings.shape[0], (
        "Invalid arrays!"
    )
    num_features = np.unique(merge_map).shape[0]
    # assert num_features <= merge_map.shape[0], "Num features must be lte size of merge map"
    line_mappings = np.zeros([num_features, 2], dtype=np.long)
    # print(f'Original merge map size {merge_map.shape}')
    # print(f'Made line mappings {line_mappings.shape}')
    # The lookup key is the target merge, the values are all nodes that were merged into it
    lookup = {}
    for i, itm in enumerate(merge_map.tolist()):
        if itm in lookup:
            lookup[itm].append(i)
        else:
            lookup[itm] = [i]

    for target, values in lookup.items():
        min_num = 999999999
        max_num = -1
        for merge_src in values:
            row = original_line_mappings[merge_src]
            low = row[0]
            high = row[1]
            min_num = min(min_num, low)
            max_num = max(max_num, high)

        line_mappings[target] = np.array([min_num, max_num])

    return line_mappings


def recombine_per_graph_spans(
    batch: NDArray,  # [N] graph‐ID per pooled node
    recovered_per_graph: list[
        NDArray
    ],  # list of [n_g,2] arrays, one per graph in same order
    selected_indices_for_batch,
) -> NDArray:
    """
    Given:
      - batch:           length‐N array, batch[i] = graph‐ID of node i
      - recovered_per_graph[k]: array [n_k,2] for graph k,
         in the same order as your `for (pid, graph) in selected_indices`
    Returns:
      - full_spans: np.ndarray of shape [N,2],
         where full_spans[i] is the span for node i.
    """
    N = batch.shape[0]
    full_spans = np.zeros((N, 2), dtype=int)

    # Suppose your graph‐loop was in this order:
    #   for idx, (pid, graph) in enumerate(selected_indices_for_batch):
    idx = 0
    for _, graph in selected_indices_for_batch:
        mask = batch == graph  # boolean mask of shape [N]

        if mask.sum() == 0:
            # Graph was removed entirely, skip!
            continue

        spans = recovered_per_graph[idx]  # shape [mask.sum(), 2]
        # sanity check:
        assert spans.shape[0] == mask.sum(), (
            f"Spans don't match mask: ({spans.shape[0]} != {mask.sum()})"
        )
        full_spans[mask] = spans  # broadcast assign into those rows
        idx += 1

    return full_spans


def calculate_line_spans(
    merge_map: NDArray,
    selected_indices_for_batch: list[tuple[int, int]],
    selected_line_assignments_for_batch: NDArray,
    batch: NDArray,
    perm: NDArray,
):
    line_spans = []

    for _persistent_id, graph in selected_indices_for_batch:
        mask = batch == graph  # select survivors of that graph
        local_pos = np.nonzero(mask)[
            0
        ]  # indices of surviving nodes in this graph

        if local_pos.size == 0:
            # Graph was completely removed, skip it
            continue

        global_nodes = perm[local_pos]  # true original indices
        merge_map_for_graph = merge_map[global_nodes]

        # Remap to 0..N_graph-1 for survivors
        uniques = np.unique(merge_map_for_graph)
        remap = {orig: i for i, orig in enumerate(uniques)}
        merge_map_for_graph = np.array([remap[v] for v in merge_map_for_graph])

        line_assignments_for_graph = selected_line_assignments_for_batch[
            global_nodes
        ]

        recovered_assignments = create_line_number_mappings(
            merge_map_for_graph, line_assignments_for_graph
        )

        node_spans = recovered_assignments[merge_map_for_graph]
        line_spans.append(node_spans)

    # recombine into full-length array; skips graphs that were removed
    recombined = recombine_per_graph_spans(
        batch, line_spans, selected_indices_for_batch
    )

    assert recombined.shape[0] == batch.shape[0], (
        f"line_spans.shape[0] ({recombined.shape[0]}) != batch.shape[0] ({batch.shape[0]})"
    )

    return recombined


def find_root_nodes(edge_index: Tensor, node_indices: Tensor) -> list[int]:
    """
    Finds root nodes in a given graph using node indices.
    A root node is one with no incoming edges.
    """
    incoming = defaultdict(int)
    for src, dst in edge_index.t().tolist():
        if dst in node_indices:
            incoming[dst] += 1

    return [
        int(node.item())
        for node in node_indices
        if incoming[int(node.item())] == 0
    ]


def preorder_traversal(edge_index: Tensor, root: int) -> list[int]:
    """
    Performs a preorder traversal (node → children) of a tree rooted at `root`.
    `edge_index` is expected to be a 2 x E tensor of directed edges.
    """
    tree = defaultdict(list)
    for src, dst in edge_index.t().tolist():
        tree[src].append(dst)

    visited = set()
    order = []

    def dfs(node):
        if node in visited:
            return
        visited.add(node)
        order.append(node)
        for child in tree[node]:
            dfs(child)

    dfs(root)
    return order


def get_projections_and_targets_for_each_batch(proj, batch, cache: Cache):
    tgt = torch.argmax(batch.x, dim=1)

    selected_batch_indices = list(range(torch.max(batch.batch) + 1))
    persistent_to_batch_id_map = list(
        zip(map(int, batch.key_index), selected_batch_indices)
    )

    batch_to_persistent_id_map = {
        bid: pid for pid, bid in persistent_to_batch_id_map
    }

    for batch_id in torch.unique(batch.batch):
        if batch_to_persistent_id_map[int(batch_id)] in cache:
            preorder = cache[batch_to_persistent_id_map[int(batch_id)]]
        else:
            subgraph_mask = batch.batch == batch_id
            node_indices = subgraph_mask.nonzero(as_tuple=True)[0]
            subgraph_edge_index, _ = subgraph(
                edge_index=batch.edge_index,
                subset=node_indices,
                relabel_nodes=True,
            )

            # Find root node(s)
            roots = find_root_nodes(
                subgraph_edge_index, torch.arange(node_indices.shape[0])
            )
            assert len(roots) == 1, "AST should have exactly one root"

            # Traverse
            preorder = preorder_traversal(subgraph_edge_index, roots[0])
            cache[batch_to_persistent_id_map[int(batch_id)]] = preorder

        def window(seq, n=2):
            it = iter(seq)
            win = deque((next(it, None) for _ in range(n)), maxlen=n)
            yield win
            append = win.append
            for e in it:
                append(e)
                yield win

        projs = []
        tgts = []
        for a, b in window(preorder):
            projs.append(proj[a])
            tgts.append(tgt[b])

        projs = torch.stack(projs)
        tgts = torch.stack(tgts)
        yield projs, tgts


def mine_triplets_from_aux_embeddings(
    x: torch.Tensor,
    embeddings: torch.Tensor,
    top_k: int = 3,
    distance_metric: str = "cosine",
) -> torch.Tensor:
    """
    Args:
        x: (N, D) one-hot node type matrix.
        embeddings: (D, E) embedding lookup for node types.
        top_k: number of types to mine for positives and negatives.
        distance_metric: 'cosine' or 'euclidean'.

    Returns:
        triplets: (T, 3) LongTensor with anchor, positive, and negative indices.
    """
    node_types = x.argmax(dim=1)  # (N,)
    N, D = x.shape

    # === 1. Compute (D, D) distance matrix between types ===
    if distance_metric == "cosine":
        type_embs = torch.nn.functional.normalize(embeddings, dim=1)
        dist_type_type = 1 - type_embs @ type_embs.T
    elif distance_metric == "euclidean":
        diff = embeddings[:, None, :] - embeddings[None, :, :]
        dist_type_type = torch.norm(diff, dim=2)
    else:
        raise ValueError("Unsupported distance metric")

    # Exclude self-types using NaN (so they don't appear in topk either way)
    dist_type_type.fill_diagonal_(float("nan"))

    # === 2. Precompute type -> indices map ===
    type_to_indices = [[] for _ in range(D)]
    for idx, t in enumerate(node_types.tolist()):
        type_to_indices[t].append(idx)

    # === 3. Mine triplets ===
    triplets = []

    for i in range(N):
        anchor_type = node_types[i]
        dists = dist_type_type[anchor_type]  # (D,)

        if dists.isnan().all():
            continue  # no other types to compare to

        # Top-k closest and farthest *types* (excluding self via NaN)
        _, closest_types = torch.topk(dists, top_k, largest=False)
        _, farthest_types = torch.topk(dists, top_k, largest=True)

        for pt in closest_types.tolist():
            pos_candidates = type_to_indices[pt]
            if not pos_candidates:
                continue
            pos_idx = pos_candidates[torch.randint(len(pos_candidates), (1,))]

            for nt in farthest_types.tolist():
                neg_candidates = type_to_indices[nt]
                if not neg_candidates:
                    continue
                neg_idx = neg_candidates[
                    torch.randint(len(neg_candidates), (1,))
                ]
                triplets.append((i, pos_idx, neg_idx))

    assert len(triplets) > 0, "Triples array empty, probably bad"

    return torch.tensor(triplets, dtype=torch.long)


class AverageAccumulator:
    def __init__(self, init: float | Tensor = 0.0) -> None:
        self.sum = init
        self.num = 0

    def __iadd__(self, o):
        self.sum += o
        self.num += 1
        return self

    def mean(self) -> float | Tensor:
        return self.sum / max(self.num, 1)


def make_persistent_to_batch_id_map(batch):
    # Selected graph indices are actually different than the assignments given by PyTorch
    # Zip them together for processing later
    selected_batch_indices = list(range(torch.max(batch.batch) + 1))
    persistent_to_batch_id_map = list(
        zip(map(int, batch.key_index), selected_batch_indices)
    )

    return persistent_to_batch_id_map


def persistent_to_batch_id_map_and_keys(
    batch, keys
) -> tuple[list[tuple[int, int]], list[NDArray], list[int]]:
    persistent_to_batch_id_map = make_persistent_to_batch_id_map(batch)

    keys_1d = []
    key_batch = []

    def add_key_to_keys_and_batch(val: NDArray, gid, target_left: bool):
        nonlocal keys_1d, key_batch
        if target_left:
            keys_1d.append(val[:, [0, 2]])
        else:
            keys_1d.append(val[:, [1, 3]])
        key_batch += [gid] * val.shape[0]

    for pid, gid in persistent_to_batch_id_map:
        for left, right in keys.keys():
            if pid == left or pid == right:
                add_key_to_keys_and_batch(keys[(left, right)], gid, pid == left)

    return persistent_to_batch_id_map, keys_1d, key_batch


def build_gats_and_layer_norms(
    dims: list[int],
    num_heads: list[int],
) -> tuple[ModuleList, ModuleList, int]:
    """
    Last head value is ignored since we are creating based on current dim output
    """
    assert len(dims) == len(num_heads) + 1
    gats = ModuleList()
    norms = ModuleList()
    for i in range(len(num_heads)):
        gats.append(
            GATv2Conv(
                dims[i] * (num_heads[i - 1] if i > 0 else 1),
                dims[i + 1],
                heads=num_heads[i],
            )
        )
        norms.append(LayerNorm(dims[i + 1] * num_heads[i]))
    return gats, norms, dims[-1] * num_heads[-1]
