from dataclasses import dataclass
from typing import Literal, NamedTuple

import numpy as np
import torch
import torch.nn.functional as F
import torch_scatter
from numpy.typing import NDArray
from progress import deque
from torch import Tensor
from torch_geometric.utils import k_hop_subgraph


class Transition(NamedTuple):
    logp: torch.Tensor  # [N]
    reward: torch.Tensor  # [G]
    value: torch.Tensor  # [G]
    batch: torch.Tensor
    entropy: torch.Tensor


class RunningNorm:
    """
    Code generated by ChatGPT: reward shaping + running normalization + masked critic loss.
    """

    def __init__(self, eps: float = 1e-8):
        self.count = 0.0
        self.mean = 0.0
        self.M2 = 0.0
        self.eps = eps

    def update(self, x: torch.Tensor):
        # x: arbitrary shape; we update with its mean to be robust
        v = x.detach().mean().item()
        self.count += 1.0
        delta = v - self.mean
        self.mean += delta / max(self.count, 1.0)
        delta2 = v - self.mean
        self.M2 += delta * delta2

    @property
    def std(self):
        if self.count < 2:
            return 1.0
        return (self.M2 / (self.count - 1.0)) ** 0.5 + self.eps

    def normalize(self, x: torch.Tensor) -> torch.Tensor:
        return (x - self.mean) / self.std


# --- reward shaping helper ---
def diou_to_reward(
    diou: torch.Tensor,
    mode: Literal["exp", "log", "lin"] = "exp",
    k: float = 4.0,
    pivot: float = 0.5,
    sharp: float = 6.0,
) -> torch.Tensor:
    """
    mode='exp' : r = exp(-k * diou)
    mode='log' : r = sigmoid(sharp * (pivot - diou))
    mode='lin' : r = 1 - diou  (clip later)
    """
    if mode == "exp":
        r = torch.exp(-k * diou)
    elif mode == "log":
        r = torch.sigmoid(sharp * (pivot - diou))
    else:
        r = 1.0 - diou
    return r


# Copied from SO
def lerp(a: float, b: float, t: float) -> float:
    """Linear interpolate on the scale given by a to b, using t as the point on that scale.
    Examples
    --------
        50 == lerp(0, 100, 0.5)
        4.2 == lerp(1, 5, 0.8)
    """
    return (1 - t) * a + t * b


def compute_reward(
    diou_l: Tensor,
    total_keys: int,
    remaining_keys: int,
    batch: Tensor,
    size_penalty: float = 0.01,
) -> Tensor:
    """
    diou_l: [N] – node‑wise DIoU (lower is better)
    missing_ratio: float - the number of keys minus the number of missing keys
    batch:  [N] – graph ID for each node
    Returns: [G] – reward per graph
    """
    # # Normalise DIoU so that lower = better
    # diou_norm = (diou_l - diou_l.mean()) / (diou_l.std() + 1e-6)

    # # Node‑wise reward = -DIoU (because lower DIoU means more accurate)
    # node_reward = -diou_norm

    node_reward = diou_to_reward(diou=diou_l, mode="log")

    # Graph‑wise mean reward
    G = batch.max().item() + 1
    reward_per_graph = torch.zeros(int(G)).to(diou_l.device)
    reward_per_graph = torch_scatter.scatter_mean(
        node_reward, batch, dim=0, out=reward_per_graph
    )

    # Size penalty – encourage fewer nodes
    num_nodes = torch_scatter.scatter_sum(torch.ones_like(diou_l), batch, dim=0)
    reward_per_graph -= size_penalty * num_nodes.float()

    # Missing graph penalty
    reward_per_graph *= remaining_keys / total_keys
    # for event in missing:
    # reward_per_graph[event] -= missing_graph_penalty

    return reward_per_graph


"""assistant-wrote: corrected returns/advantages with per-layer standardization"""


def compute_returns_and_advantages(
    transitions,
    gamma: float = 0.99,
    lam: float = 0.95,
    reward_last_only: bool = False,
    standardize_adv: bool = True,
):
    # Figure out the maximum number of graphs across all transitions
    max_G = max(t.reward.shape[0] for t in transitions)
    L = len(transitions)

    # Pad rewards/values to [L, max_G], and keep a mask
    R = torch.zeros(L, max_G, device=transitions[0].reward.device)
    V = torch.zeros(L, max_G, device=transitions[0].reward.device)
    V_critic = torch.zeros(L, max_G, device=transitions[0].reward.device)
    mask = torch.zeros(L, max_G, dtype=torch.bool, device=R.device)

    for i, t in enumerate(transitions):
        g = t.reward.shape[0]
        R[i, :g] = t.reward
        V[i, :g] = t.value.detach()
        V_critic[i, :g] = t.value
        mask[i, :g] = True

    if reward_last_only:
        R[:-1] = R[-1].unsqueeze(0)

    returns = torch.zeros_like(R)
    gae = torch.zeros(max_G, device=R.device)

    # Compute GAE backwards in time
    for t in reversed(range(L)):
        v_t = V[t]
        v_tp1 = V[t + 1] if t + 1 < L else torch.zeros_like(v_t)
        delta = R[t] + gamma * v_tp1 - v_t
        gae = delta + gamma * lam * gae
        returns[t] = gae + v_t

    advantages = returns - V

    # Mask out invalid graphs
    returns = returns * mask
    advantages = advantages * mask

    if standardize_adv:
        eps = 1e-8
        # avoid dividing by zero for masked-out entries
        mean = (
            advantages.sum(dim=1, keepdim=True)
            / mask.sum(dim=1, keepdim=True).clamp(min=1)
        ).detach()
        var = ((advantages - mean) ** 2 * mask).sum(
            dim=1, keepdim=True
        ) / mask.sum(dim=1, keepdim=True).clamp(min=1)
        std = var.sqrt().clamp(min=eps)
        advantages = (advantages - mean) / std

    advantages = torch.clamp(advantages, -10.0, 10.0)
    return returns, advantages, R, V_critic, mask


@dataclass
class Metrics:
    actor_loss: Tensor
    critic_loss: Tensor
    reward: Tensor
    value: Tensor
    entropy: Tensor


def actor_critic_loss(
    transitions: list[Transition],
    gamma: float = 0.99,
    lam: float = 0.95,
    entropy_coef: float = 0.01,
) -> Metrics:
    """
    transitions : list[Transition] – all layers
    returns    : [G]
    advantages : [G]
    """
    returns, advantages, R, V, mask = compute_returns_and_advantages(
        transitions,
        gamma,
        lam,
    )

    # Policy loss (PG)
    actor_loss = 0.0
    entropy_terms = []
    for i, transition in enumerate(transitions):
        actor_loss += -(
            advantages[i][transition.batch] * transition.logp
        ).mean()
        entropy_terms.append(transition.entropy)

    # Critic loss (smooth L1 / Huber)
    V_all = V.reshape([-1])
    # V_all = torch.cat([t.value for t in transitions])  # [L, G]
    R_all = torch.cat([returns[t] for t in range(len(returns))])  # [L, G]
    assert V_all.shape == R_all.shape, (
        f"Shapes mismatch: V_all: {V_all.shape} R_all: {R_all.shape}"
    )
    critic_loss = F.mse_loss(V_all, R_all)

    # Entropy bonus
    entropy = (
        torch.cat(entropy_terms, dim=0).mean()
        if entropy_terms
        else torch.tensor(0.0, device=transitions[0].logp.device)
    )
    actor_loss -= entropy_coef * entropy

    return Metrics(
        actor_loss=actor_loss,
        critic_loss=critic_loss,
        value=V_all,
        reward=R_all,
        entropy=entropy,
    )


def diou_loss_1d(a: NDArray, b: NDArray) -> NDArray:
    EPSILON = 1e-6

    if a.ndim == 1:
        a = np.expand_dims(a, 0)
    if b.ndim == 1:
        b = np.expand_dims(b, 0)

    assert a.ndim == 2 and b.ndim == 2 and a.shape[1] == b.shape[1] == 2, (
        f"Bad data: a: {a.shape} b: {b.shape}"
    )
    a, b = np.broadcast_arrays(a, b)

    a_center = np.mean(a, axis=1)
    b_center = np.mean(b, axis=1)
    dist_sq = (a_center - b_center) ** 2
    farthest_end = np.max(
        np.hstack([a[:, 1][:, None], b[:, 1][:, None]]), axis=1
    )
    closest_start = np.min(
        np.hstack([a[:, 0][:, None], b[:, 0][:, None]]), axis=1
    )
    outer_distance_sq = (farthest_end - closest_start) ** 2

    start = np.max(np.hstack([a[:, 0][:, None], b[:, 0][:, None]]), axis=1)
    end = np.min(np.hstack([a[:, 1][:, None], b[:, 1][:, None]]), axis=1)
    valid = start < end
    intersection = np.hstack((start[:, None], end[:, None]))
    intersection[~valid] = 0
    intersection = np.diff(intersection, axis=1)
    union = (np.diff(a, axis=1) + np.diff(b, axis=1)) - intersection
    iou_old = intersection / (union + EPSILON)

    # Cleaner impl from ChatGPT
    inter_len = np.clip(end - start, 0, None)
    a_len = a[:, 1] - a[:, 0]
    b_len = b[:, 1] - b[:, 0]
    union = a_len + b_len - inter_len
    iou = inter_len / (union + EPSILON)

    assert np.all(np.equal(iou, iou_old.squeeze(1))), (
        f"DIOU doesnt match old {iou_old.squeeze(1)} != new {iou}"
    )

    return 1.0 - iou + dist_sq / (outer_distance_sq + EPSILON)


def find_closest_mapping_index(line_mappings: NDArray, target: NDArray) -> int:
    return np.argmin(diou_loss_1d(line_mappings, target)).astype(int)


def diou_loss(
    line_mappings: NDArray,
    edge_index: NDArray,
    batch: NDArray,
    keys: NDArray,
    key_batch_associations: NDArray,
    k: int = 5,
    decay_alpha: float = 0.5,
    log_transform_diou: bool = True,
) -> tuple[Tensor, list[int]]:
    """
    Calculates DIoU loss for the closest node in the graph to each key (based on DIoU) and fans out `k` hops
    with decay `decay_alpha`
    """

    assert line_mappings.shape[0] == batch.shape[0], (
        f"line_mappings.shape[0] ({line_mappings.shape[0]}) != batch.shape[0] ({batch.shape[0]})"
    )
    num_nodes = line_mappings.shape[0]

    # Shuffle keys to make it slightly more stochastic
    np.random.shuffle(keys)
    # Find the absolute best nodes (lowest DIoU loss) for each key
    best_node_indices = []
    missing_entry_events = []
    for i, key in enumerate(keys):
        mask = batch == key_batch_associations[i]
        if len(line_mappings[mask]) == 0:
            missing_entry_events += [key_batch_associations[i]] * key.shape[0]
            continue
        map_to_original = np.arange(batch.shape[0])[mask]
        best_node_indices.append(
            map_to_original[
                find_closest_mapping_index(line_mappings[mask], key)
            ]
        )
        # print(f'Best index for {key} is {best_node_indices[-1]} (with value {line_mappings[best_node_indices[-1]]}) from \n {line_mappings[mask]} w/loss\n {diou_loss_1d(line_mappings[mask], key)}')

    # Do k hop subgraph for each key, assigning the DIoU to each node in the graph
    edge_index: Tensor = torch.tensor(edge_index)
    subset, edge_index, mapping, edge_mask = k_hop_subgraph(
        best_node_indices,
        num_hops=k,
        edge_index=edge_index,
        num_nodes=num_nodes,
    )

    # Always want to add DIoU loss since multiple spans can be close enough to eachother for them to overlap

    # ChatGPT made this
    def decay_fn(depth: int):
        return decay_alpha**depth

    # Initialize full loss vector (global node indices)
    losses_full = torch.zeros(num_nodes, dtype=torch.float)

    # Build adjacency list for full graph
    adj = [[] for _ in range(num_nodes)]
    for src, dst in edge_index.t().tolist():
        adj[src].append(dst)
        adj[dst].append(src)  # if undirected

    # Propagate DIoU loss from each source node
    for i, node_index in enumerate(best_node_indices):
        diou_val = torch.tensor(
            diou_loss_1d(line_mappings[node_index], keys[i])
        )
        if log_transform_diou:
            diou_val = torch.log(diou_val + 1e-8)
        # print(f'Loss for node {node_index} is {diou_val} using {line_mappings[node_index]} and {keys[i]}')

        visited = set()
        queue = deque()
        queue.append((node_index, 0))  # (current_node, depth)

        while queue:
            current, depth = queue.popleft()
            if current in visited or depth > k:
                continue
            visited.add(current)

            losses_full[current] += diou_val.sum(dim=0) * decay_fn(depth)

            if depth < k:
                for neighbor in adj[current]:
                    if neighbor not in visited:
                        queue.append((neighbor, depth + 1))

    return losses_full, missing_entry_events


def create_line_number_mappings(
    merge_map: NDArray, original_line_mappings: NDArray
) -> NDArray:
    """
    Takes the `merge_map` of shape `[N]` generated by the model run and `original_line_mappings` of shape `[N, 2]`
    Uses an iterative algorithm to determine merges for each item in the merge map.
    The returned tensor contains the feature and it's start and end line numbers
    """
    assert merge_map.shape[0] == original_line_mappings.shape[0], (
        "Invalid arrays!"
    )
    num_features = np.unique(merge_map).shape[0]
    # assert num_features <= merge_map.shape[0], "Num features must be lte size of merge map"
    line_mappings = np.zeros([num_features, 2], dtype=np.long)
    # print(f'Original merge map size {merge_map.shape}')
    # print(f'Made line mappings {line_mappings.shape}')
    # The lookup key is the target merge, the values are all nodes that were merged into it
    lookup = {}
    for i, itm in enumerate(merge_map.tolist()):
        if itm in lookup:
            lookup[itm].append(i)
        else:
            lookup[itm] = [i]

    for target, values in lookup.items():
        min_num = 999999999
        max_num = -1
        for merge_src in values:
            row = original_line_mappings[merge_src]
            low = row[0]
            high = row[1]
            min_num = min(min_num, low)
            max_num = max(max_num, high)

        line_mappings[target] = np.array([min_num, max_num])

    return line_mappings


def recombine_per_graph_spans(
    batch: NDArray,  # [N] graph‐ID per pooled node
    recovered_per_graph: list[
        NDArray
    ],  # list of [n_g,2] arrays, one per graph in same order
    selected_indices_for_batch,
) -> NDArray:
    """
    Given:
      - batch:           length‐N array, batch[i] = graph‐ID of node i
      - recovered_per_graph[k]: array [n_k,2] for graph k,
         in the same order as your `for (pid, graph) in selected_indices`
    Returns:
      - full_spans: np.ndarray of shape [N,2],
         where full_spans[i] is the span for node i.
    """
    N = batch.shape[0]
    full_spans = np.zeros((N, 2), dtype=recovered_per_graph[0].dtype)

    # Suppose your graph‐loop was in this order:
    #   for idx, (pid, graph) in enumerate(selected_indices_for_batch):
    idx = 0
    for _, graph in selected_indices_for_batch:
        mask = batch == graph  # boolean mask of shape [N]

        if mask.sum() == 0:
            # Graph was removed entirely, skip!
            continue

        spans = recovered_per_graph[idx]  # shape [mask.sum(), 2]
        # sanity check:
        assert spans.shape[0] == mask.sum(), (
            f"Spans don't match mask: ({spans.shape[0]} != {mask.sum()})"
        )
        full_spans[mask] = spans  # broadcast assign into those rows
        idx += 1

    return full_spans


def calculate_line_spans(
    merge_map: NDArray,
    selected_indices_for_batch: list[tuple[int, int]],
    selected_line_assignments_for_batch: NDArray,
    batch: NDArray,
    perm: NDArray,
):
    line_spans = []

    for _persistent_id, graph in selected_indices_for_batch:
        mask = batch == graph  # select survivors of that graph
        local_pos = np.nonzero(mask)[
            0
        ]  # indices of surviving nodes in this graph

        if local_pos.size == 0:
            # Graph was completely removed, skip it
            continue

        global_nodes = perm[local_pos]  # true original indices
        merge_map_for_graph = merge_map[global_nodes]

        # Remap to 0..N_graph-1 for survivors
        uniques = np.unique(merge_map_for_graph)
        remap = {orig: i for i, orig in enumerate(uniques)}
        merge_map_for_graph = np.array([remap[v] for v in merge_map_for_graph])

        line_assignments_for_graph = selected_line_assignments_for_batch[
            global_nodes
        ]

        recovered_assignments = create_line_number_mappings(
            merge_map_for_graph, line_assignments_for_graph
        )

        node_spans = recovered_assignments[merge_map_for_graph]
        line_spans.append(node_spans)

    # recombine into full-length array; skips graphs that were removed
    recombined = recombine_per_graph_spans(
        batch, line_spans, selected_indices_for_batch
    )

    assert recombined.shape[0] == batch.shape[0], (
        f"line_spans.shape[0] ({recombined.shape[0]}) != batch.shape[0] ({batch.shape[0]})"
    )

    return recombined
